
[common]

	[common.worldgen]
		#NOT YET IMPLEMENTED: Set to true if waystones should be added to the generation of villages. THIS OPTION DOES NOT WORK YET.
		addVillageStructure = false
		#Approximate chunk distance between waystones generated freely in world generation. Set to 0 to disable generation.
		#Range: > 0
		worldGenFrequency = 0
		#Set to 'DEFAULT' to only generate the normally textured waystones. Set to 'MOSSY' or 'SANDY' to generate all as that variant. Set to 'BIOME' to make the style depend on the biome it is generated in.
		#Allowed Values: DEFAULT, MOSSY, SANDY, BIOME
		worldGenStyle = "BIOME"
		#The Name Generator will pick from these names until they have all been used, then it will generate random ones again.
		customWaystoneNames = ["DOGGOD", "Tunaville", "bluena", "Pancakes", ":D :D", "Your admins are the best!", "Admin Aboose = Mute", "Death by Puppies!!!", "Banhammer", "Zach's Hole", "Alliance", "Ugly Base", "These configs have been modified"]

